#!/bin/bash

set -eu

if [ ! -d ../../../ableC ]; then
    echo "Expected to this repository to be checked out in an extensions/ folder at the same level as the ableC."
fi

if [ ! -f ../../../ableC/ableC.jar ]; then
    echo "Build ableC.jar first by running the build script in the ableC directory."
fi

if [ ! -f ../ableC-skeleton.jar ]; then
    echo "Build ableC-skeleton.jar first by running 'make build' in the ableC-skeleton directory."
fi

set -x

silver -I ../ableC-skeleton.jar -I ../../../ableC/ableC.jar -I ../grammars -o compiler.jar $@ edu:umn:cs:melt:exts:ableC:skeleton:artifacts:compiler
java -Xss8M -jar compiler.jar skeleton.xc
gcc -c skeleton.c -o skeleton.o
gcc skeleton.o -o skeleton.out
./skeleton.out